Data Preparation:

In [50]:
import pandas as pd
df=pd.read_excel("transactions.xlsx")
df

,Transaction ID,From Account Name,To Account Name,From Account Number,To Account Number,Amount Transfer,From Country,To Country,From Country Code,To Country Code,Suspicious Value,Risk,Mode of Transaction
0,1,John Doe,Jane Smith,1230000000,9880000000,1000,USA,UK,840,826,0,Low,Wire Transfer
1,2,Alice Johnson,Bob Brown,9880000000,1230000000,500,Canada,Australia,124,36,0,Low,Cash Deposit
2,3,Sarah Lee,Michael Wang,2350000000,8770000000,2000,Germany,China,276,156,0,Low,Online Transfer
3,4,Anna Wong,Eriksson Karlsson,556000000,889000000,50000,Iceland,Sweden,352,752,1,High,Wire Transfer
4,5,Maria Rossi,Henrik Andersen,111000000,445000000,7500,Finland,Norway,246,578,1,High,Online Transfer
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Sanchez Martin,Martinez Gomez,111000000,445000000,950,Spain,Portugal,724,620,0,Low,Cash Deposit
96,97,Park Min-ji,Kim Seo-joon,1000000000,667000000,2700,South Korea,Japan,410,392,0,Low,Online Transfer
97,98,Samantha White,Michael Brown,124000000,654000000,2600,USA,Canada,840,124,0,Low,Wire Transfer
98,99,Luca Bianchi,Giulia Ferrari,889000000,555000000,800,Italy,France,380,250,0,Low,Cash Deposit
99,100,Müller Schmidt,Wagner Becker,222000000,556000000,5100,Germany,Austria,276,40,0,Low,Online Transfer

In [51]:
#Output Value
y=df['Suspicious Value']
y

0     0
1     0
2     0
3     1
4     1
     ..
95    0
96    0
97    0
98    0
99    0
Name: Suspicious Value, Length: 100, dtype: int64

In [52]:
#Dropping of Transaction Id and Suspicious value from training data
x=df.drop(columns=['Transaction ID','Suspicious Value'])
x

,From Account Name,To Account Name,From Account Number,To Account Number,Amount Transfer,From Country,To Country,From Country Code,To Country Code,Risk,Mode of Transaction
0,John Doe,Jane Smith,1230000000,9880000000,1000,USA,UK,840,826,Low,Wire Transfer
1,Alice Johnson,Bob Brown,9880000000,1230000000,500,Canada,Australia,124,36,Low,Cash Deposit
2,Sarah Lee,Michael Wang,2350000000,8770000000,2000,Germany,China,276,156,Low,Online Transfer
3,Anna Wong,Eriksson Karlsson,556000000,889000000,50000,Iceland,Sweden,352,752,High,Wire Transfer
4,Maria Rossi,Henrik Andersen,111000000,445000000,7500,Finland,Norway,246,578,High,Online Transfer
...,...,...,...,...,...,...,...,...,...,...,...
95,Sanchez Martin,Martinez Gomez,111000000,445000000,950,Spain,Portugal,724,620,Low,Cash Deposit
96,Park Min-ji,Kim Seo-joon,1000000000,667000000,2700,South Korea,Japan,410,392,Low,Online Transfer
97,Samantha White,Michael Brown,124000000,654000000,2600,USA,Canada,840,124,Low,Wire Transfer
98,Luca Bianchi,Giulia Ferrari,889000000,555000000,800,Italy,France,380,250,Low,Cash Deposit
99,Müller Schmidt,Wagner Becker,222000000,556000000,5100,Germany,Austria,276,40,Low,Online Transfer

Converting String-data columns to numeric values

In [53]:
from sklearn.preprocessing import LabelEncoder
label_encoders = {}
categorical_columns = ['From Account Name', 'From Country', 'To Account Name', 'To Country', 'Mode of Transaction', 'Risk']

for column in categorical_columns:
    label_encoders[column] = LabelEncoder()
    x[column] = label_encoders[column].fit_transform(x[column])
x

,From Account Name,To Account Name,From Account Number,To Account Number,Amount Transfer,From Country,To Country,From Country Code,To Country Code,Risk,Mode of Transaction
0,14,11,1230000000,9880000000,1000,13,17,840,826,1,2
1,1,2,9880000000,1230000000,500,0,0,124,36,1,0
2,38,22,2350000000,8770000000,2000,4,4,276,156,1,1
3,6,5,556000000,889000000,50000,5,15,352,752,0,2
4,25,9,111000000,445000000,7500,3,10,246,578,0,1
...,...,...,...,...,...,...,...,...,...,...,...
95,37,20,111000000,445000000,950,11,11,724,620,1,0
96,33,14,1000000000,667000000,2700,10,9,410,392,1,1
97,36,21,124000000,654000000,2600,13,3,840,124,1,2
98,22,7,889000000,555000000,800,6,6,380,250,1,0
99,29,38,222000000,556000000,5100,4,1,276,40,1,1

Data Splitting

In [54]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=0.2, random_state=100)

In [55]:
x_train

,From Account Name,To Account Name,From Account Number,To Account Number,Amount Transfer,From Country,To Country,From Country Code,To Country Code,Risk,Mode of Transaction
29,35,35,222000000,556000000,4200,4,1,276,40,1,1
83,34,0,222000000,556000000,3600,2,10,208,578,1,2
82,30,37,889000000,555000000,1300,14,2,704,116,1,1
43,34,0,222000000,556000000,3700,2,10,208,578,1,2
28,0,18,889000000,555000000,600,6,6,380,250,1,0
...,...,...,...,...,...,...,...,...,...,...,...
79,29,38,222000000,556000000,5000,4,1,276,40,1,1
87,39,3,124000000,654000000,2700,13,3,840,124,1,2
67,39,3,124000000,654000000,2800,13,3,840,124,1,2
24,16,27,988000000,123000000,1800,9,7,616,276,1,1
8,26,4,124000000,654000000,2800,4,12,276,643,1,1

In [56]:
x_test

,From Account Name,To Account Name,From Account Number,To Account Number,Amount Transfer,From Country,To Country,From Country Code,To Country Code,Risk,Mode of Transaction
37,36,21,124000000,654000000,2200,13,3,840,124,1,2
62,30,37,889000000,555000000,1400,14,2,704,116,1,1
26,20,13,1000000000,667000000,2200,10,9,410,392,1,1
41,21,26,778000000,111000000,1000,1,9,156,392,1,0
35,37,20,111000000,445000000,850,11,11,724,620,1,0
25,27,32,111000000,445000000,800,11,11,724,620,1,0
36,33,14,1000000000,667000000,2600,10,9,410,392,1,1
33,3,28,222000000,556000000,3000,2,10,208,578,1,2
77,36,21,124000000,654000000,2500,13,3,840,124,1,2
21,7,39,778000000,111000000,700,1,9,156,392,1,0
85,27,32,111000000,445000000,850,11,11,724,620,1,0
50,19,24,556000000,889000000,5700,12,10,752,578,0,2
92,31,36,889000000,555000000,1200,14,2,704,116,1,1
69,35,35,222000000,556000000,4500,4,1,276,40,1,1
96,33,14,1000000000,667000000,2700,10,9,410,392,1,1
78,22,7,889000000,555000000,800,6,6,380,250,1,0
72,31,36,889000000,555000000,1500,14,2,704,116,1,1
5,9,8,778000000,333000000,12000,12,5,752,208,0,2
40,10,12,556000000,889000000,6300,12,10,752,578,0,2
11,4,25,222000000,556000000,4000,8,5,578,208,1,1

Model Building

Decission Tree model

In [57]:
from sklearn.tree import DecisionTreeClassifier

dt_model= DecisionTreeClassifier()
dt_model.fit(x_train,y_train)

DecisionTreeClassifier()

Testing the model

In [58]:
y_dt_model_train_pred=dt_model.predict(x_train)
y_dt_model_test_pred=dt_model.predict(x_test)

In [59]:
y_dt_model_test_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0])

Accuracy

In [60]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

accuracy = accuracy_score(y_test, y_dt_model_test_pred)
print(f"Accuracy: {accuracy:.2f}")
Randomforest_report = classification_report(y_test,y_dt_model_test_pred)
print(Randomforest_report)

Accuracy: 1.00
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00         3

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

saving the trained model using joblib

In [61]:
import joblib
model_filename = 'DecisionTree_model.pkl'
joblib.dump(dt_model, model_filename)
model_filename  # Return the filename where the model is saved

'DecisionTree_model.pkl'

RandomForest model

In [62]:
from sklearn.ensemble import RandomForestClassifier

rf_model= RandomForestClassifier()
rf_model.fit(x_train,y_train)

RandomForestClassifier()

Testing the model

In [63]:
y_rf_model_train_pred=rf_model.predict(x_train)
y_rf_model_test_pred=rf_model.predict(x_test)

In [64]:
y_rf_model_test_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0])

Accuracy and classification Report:

In [65]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
accuracy = accuracy_score(y_test, y_rf_model_test_pred)
print(f"Accuracy: {accuracy:.2f}")

Randomforest_report = classification_report(y_test,y_rf_model_test_pred)
print(Randomforest_report)

Accuracy: 1.00
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00         3

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

saving the trained model using joblib

In [66]:
import joblib
model_filename = 'Randomforest_model.pkl'
joblib.dump(rf_model, model_filename)
model_filename  # Return the filename where the model is saved

'Randomforest_model.pkl'

Testing out with new Data

In [67]:
test_data = pd.read_excel('test_data.xlsx')

label_encoders = {}
categorical_column = ['From Account Name', 'From Country', 'To Account Name', 'To Country', 'Mode of Transaction', 'Risk']
for column in categorical_column:
        if column in test_data.columns:
            label_encoders[column] = LabelEncoder()
            test_data[column] = label_encoders[column].fit_transform(test_data[column])

new_X = test_data.drop(columns=['Transaction ID', 'Suspicious Value'])

Testing out with Random Forest Algorithm

In [68]:
model = joblib.load('Randomforest_model.pkl')
    # Make predictions using the loaded model
predictions = model.predict(new_X)
print("Suspicious detection using Random Forest Algorithm:")
predictions

Suspicious detection using Random Forest Algorithm:

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

Testing out with Decision Tree Algorithm

In [69]:
model = joblib.load('DecisionTree_model.pkl')
    # Make predictions using the loaded model
predictions = model.predict(new_X)
print("Suspicious detection using Decision tree Algorithm:")
predictions

Suspicious detection using Decision tree Algorithm:

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

Printing test_data Table for cross validation:

In [71]:
TestData=pd.read_excel('test_data.xlsx')
TestData

,Transaction ID,From Account Name,To Account Name,From Account Number,To Account Number,Amount Transfer,From Country,To Country,From Country Code,To Country Code,Suspicious Value,Risk,Mode of Transaction
0,101,Sofia Eriksson,Magnus Andersson,333000000,667000000,58000,Sweden,Denmark,752,208,NaN,High,Wire Transfer
1,102,Janne Niemi,Pekka Virtanen,111000000,445000000,42000,Finland,Estonia,246,233,NaN,High,Online Transfer
2,103,Miguel Gonzalez,Marta Fernandez,889000000,556000000,30000,Spain,Andorra,724,20,NaN,High,Wire Transfer
3,104,Hans Olsen,Lars Jensen,222000000,556000000,25000,Denmark,Norway,208,578,NaN,High,Online Transfer
4,105,Chihiro Tanaka,Yuki Yamamoto,778000000,111000000,18000,Japan,New Zealand,392,554,NaN,High,Cash Deposit
5,106,Laura Mäkinen,Matti Virtanen,445000000,778000000,35000,Finland,Sweden,246,752,NaN,High,Online Transfer
6,107,Alessandro Costa,Giovanni Ricci,555000000,889000000,40000,Italy,San Marino,380,674,NaN,High,Wire Transfer
7,108,Katrine Nielsen,Anders Petersen,333000000,667000000,21000,Denmark,Sweden,208,752,NaN,High,Online Transfer
8,109,Kaspars Balodis,Anna Kuznetsova,778000000,222000000,28000,Latvia,Lithuania,428,440,NaN,High,Wire Transfer
9,110,Tanel Sepp,Jaanika Laan,1000000000,667000000,32000,USA,USA,840,840,NaN,Low,Online Transfer